# Generated by Django 3.1.2 on 2020-11-01 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionSite',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionSitePersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_site_id', models.IntegerField()),
                ('worker_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('registration_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.CharField(editable=False, max_length=32, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=1)),
                ('nation', models.CharField(max_length=8)),
                ('id_number', models.CharField(max_length=20)),
                ('residential_address', models.CharField(max_length=20)),
                ('registration_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
