# Generated by Django 3.1.2 on 2020-11-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConstructionSitePersonnel',
        ),
        migrations.AddField(
            model_name='worker',
            name='site_id',
            field=models.IntegerField(default=-1),
        ),
    ]
