# Generated by Django 3.1.2 on 2020-11-02 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spms', '0003_auto_20201102_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='registration_data',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
