# Generated by Django 3.1.2 on 2020-11-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spms', '0004_auto_20201102_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionsite',
            name='id',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='constructionsite',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.AutoField(auto_created=True, default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
