# Generated by Django 3.1.2 on 2020-11-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spms', '0006_auto_20201102_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
