# Generated by Django 3.1.1 on 2020-10-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201030_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
