# Generated by Django 3.1.1 on 2020-10-30 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201030_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
