# Generated by Django 3.1.2 on 2020-10-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201031_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cookie',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
    ]
