# Generated by Django 3.1.2 on 2020-10-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201031_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.IntegerField(default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
