# Generated by Django 3.1.2 on 2020-10-31 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201031_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cookie',
        ),
    ]
