# Generated by Django 3.1.2 on 2020-10-31 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201031_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cookie',
            new_name='token',
        ),
    ]
